### ISSUE TITLE
PyPI release tags are not present in repository

### ISSUE THREAD

**Issue by awvwgk** [zadorlab/sella#12]
While there is only a single tag in this repository, several versions are published on PyPI: https://pypi.org/project/Sella/#history. Would be useful to actually have at least tags in this repository for each release.

**Comment by ehermes** [comment]
I've added tags for all of the releases that came after v1.0.3, but earlier releases may not correspond neatly to individual commits in the history (I was a bit fast and loose with this repository at the time). v1.0.3 was the first real, usable release of Sella anyway, notwithstanding the preproduction-quality release we used for our original 2019 paper.

**Comment by awvwgk** [comment]
Thanks
