### ISSUE TITLE
from jax.config import config is deprecated

### ISSUE THREAD

**Issue by sylvester-zhang** [zadorlab/sella#39]
Hi,
sella/__init__.py currently has "from jax.config import config" but jax will now fail to let this work. I patched it on my machine to just use "jax.config.update("jax_enable_x64", True)" instead.

**Comment by Andrew-S-Rosen** [comment]
This was patched in https://github.com/zadorlab/sella/pull/36.

**Comment by Andrew-S-Rosen** [comment]
@juditzador this can be closed.

**Comment by juditzador** [comment]
OK, thanks.
