### ISSUE TITLE
Error while running IRC

### ISSUE THREAD

**Issue by PattanaikL** [zadorlab/sella#8]
Hello! I'm trying to run an IRC calculation on my TS, but I'm running into the following error:

![image](https://user-images.githubusercontent.com/35496600/156269671-0a921c94-8cc7-4f26-a0f3-d1b85cc4c50e.png)

I suspect this is related to #4, since the error occurs when obtaining the Hessian of the constraints. `irc.pes.curr["L"]` is `None` which may be an issue.

Please let me know if you'd like additional details to reproduce the error. Thank you!

**Comment by ehermes** [comment]
Can you share a minimal script that reproduces this error? Any Calculator is fine.

**Comment by PattanaikL** [comment]
Sure thing!

```
import numpy as np
from sella import IRC
from ase import Atoms
from ase.calculators.emt import EMT

numbers = [6, 6, 8, 6, 7, 6, 8, 1, 1, 1, 1, 1, 1, 1, 1, 1]
positions = np.array([[ 1.6527,  0.1839,  0.5471],
                      [ 0.8306, -0.7019, -0.3921],
                      [ 0.1444, -1.7057,  0.3074],
                      [-0.1588,  0.1407, -1.2323],
                      [-1.0435,  0.9014, -0.3839],
                      [-1.9624,  0.3492,  0.3955],
                      [-2.6059,  1.2438,  1.1877],
                      [ 2.2265,  0.9113, -0.021 ],
                      [ 1.0005,  0.7078,  1.243 ],
                      [ 2.3375, -0.4341,  1.1212],
                      [ 1.5007, -1.2317, -1.0781],
                      [-0.59  , -1.2882,  0.7884],
                      [ 0.389 ,  0.8214, -1.8838],
                      [-0.7507, -0.5456, -1.8453],
                      [-0.8885,  1.9072, -0.2888],
                      [-2.9743,  0.1089,  0.9871]])

atoms = Atoms(positions=positions, numbers=numbers)
atoms.calc = EMT()

irc = IRC(atoms, trajectory="irc.traj")
irc.run()
```

**Comment by ehermes** [comment]
Note that the IRC module is still broken for reasons I have not had time to debug, though hopefully I will be able to look into it in the near future.

**Comment by PattanaikL** [comment]
Yeah, I get `Inner IRC loop failed to converge` for every run. If you have any suggestions on how to get it working in the meantime, please let me know!

**Comment by ehermes** [comment]
@PattanaikL Can you please try your tests on the [irc_fix](/zadorlab/sella/tree/irc_fix) branch? I corrected a few oversights that may resolve the convergence failures you're seeing.

**Comment by PattanaikL** [comment]
Thanks! I ran a few, and now, not all the tests are failing. I ran 10 examples, and all but 2 failed (7 in one direction and 1 in both directions). For the two that succeeded, they fell to the same minima. Do you have suggestions to improve the convergence? Or do you think it's internal Sella bugs?

**Comment by ehermes** [comment]
This is definitely an internal Sella bug. I hope to fix this at some point, but unfortunately it's a lower priority right now.
